version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/user-management
    depends_on:
      - db
    command: "uvicorn main:app --host=0.0.0.0 --port=8000 --reload"

  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: user-management-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_mgt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: